spring.application.name=voyager

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/voyagerdb
spring.datasource.username=postgres
spring.datasource.password=123456789
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Repertoire pour les photos des utilisateurs
app.upload.dir.profiles=/app/uploads/profiles
# Repertoire pour les logos des companys
app.upload.dir.compagnies=/app/uploads/compagnies
# Repertoire pour les docs des Structures
app.upload.dir.documents=/app/uploads/documents

# Configuration pour servir des fichiers statiques
logging.level.org.springframework=DEBUG
logging.level.org.springframework.security=DEBUG
#logging.level.org.springframework.mail=DEBUG
#logging.level.org.springframework.mail.javamail=DEBUG
# debug Spring Mail & JavaMail
#spring.mail.properties.mail.debug=true


# Parametres de connexion au serveur SMTP
#spring.mail.host=eservices-gabon.com
#spring.mail.port=465
#spring.mail.username=notify@eservices-gabon.com
#spring.mail.password=O930UKZ5Pa25
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.protocol=smtp
#spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.host=solutech-one.com
spring.mail.port=465
spring.mail.username=noreply@solutech-one.com
spring.mail.password=5qUlANOYx7P!
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.ssl.enable=true

# Augmenter la taille maximale du fichier telecharge
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
spring.thymeleaf.check-template-location=false
